### PR TITLE
 Set default value of Prediction to "Unknown"

### PR DESCRIPTION
**Pull request by siayush**
Set the default value of Prediction to "Unknown"
and some minor changes in predict.py

### CODE REVIEW

**Comment by arungarg14** [comment]
Okay ayush!
I will surely do that...

**Comment by siayush** [comment]
please check the pull request. I already summited the commit regarding this issue.

**Comment by arungarg14** [comment]
Hey bro!
My distro has crashed since a week. Also, my exam is going on. It will end
on 13 Dec.
I will surely check your request...
Keep some patience.

**Comment by siayush** [comment]
oK sure take your time.

**Comment by arungarg14** [comment]
Hey! @siAyush . There is problem in it. I don't know  which case you took. But, it is not showing anything 'Unknown'. Check it out and make another pull request....

**Comment by siayush** [comment]
ok i try to fix it.

**Pull request merged**
